### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by jerryw0** [hequan2017/zabbix-models#1]
hi,
   ansible 2.4.2.0 环境运行test_inventory.py报错，如下：
Traceback (most recent call last):
  File "test_inventory.py", line 63, in <module>
    Test()
  File "test_inventory.py", line 44, in Test
    inventory = BaseInventory(host_list=host_list)
  File "/root/ansible_run/inventory.py", line 108, in __init__
    super().__init__(self.loader)
TypeError: super() takes at least 1 argument (0 given)

**Comment by jerryw0** [comment]
Python3.4 is not a supported version of python. We require at least python3.5 or newer.
